@extends('admin.layout')
@section('content')
<div class="novaos-form-hero"><div><span>NOVAOS · RELEASE BUILDER</span><h2>{{ $release->exists ? 'Edit NOVAOS release' : 'Create NOVAOS release' }}</h2><p>Publish a complete operating-system build with version, codename, build number, architecture and an automatically calculated SHA-256 checksum.</p></div><img src="{{ asset('images/projects/novaos.png') }}" alt="NOVAOS"></div>
<form class="admin-form-card novaos-form" method="POST" enctype="multipart/form-data" action="{{ $release->exists ? route('admin.novaos.releases.update',$release) : route('admin.novaos.releases.store') }}">
@csrf @if($release->exists) @method('PUT') @endif
<div class="novaos-form-section"><div class="novaos-form-section-title"><span>VERSION IDENTITY</span><strong>What users will see</strong></div><div class="form-grid three"><label>Version<input name="version" value="{{ old('version',$release->version) }}" placeholder="2026.2.1" required></label><label>Major version<input name="major_version" value="{{ old('major_version',$release->major_version) }}" placeholder="2026.2" required></label><label>Build number<input name="build_number" value="{{ old('build_number',$release->build_number) }}" placeholder="262.9437.185" required></label></div><div class="form-grid two"><label>Codename<input name="codename" value="{{ old('codename',$release->codename) }}" placeholder="Aurora"></label><label>Release channel<select name="channel">@foreach(['Stable','Beta','Nightly'] as $channel)<option value="{{ $channel }}" @selected(old('channel',$release->channel)===$channel)>{{ $channel }}</option>@endforeach</select></label></div></div>
<div class="novaos-form-section"><div class="novaos-form-section-title"><span>BUILD TARGET</span><strong>Independent OS distribution</strong></div><div class="form-grid two"><label>Architecture<select name="architecture">@foreach(['x64','ARM64'] as $arch)<option value="{{ $arch }}" @selected(old('architecture',$release->architecture)===$arch)>{{ $arch }}</option>@endforeach</select></label><label>Distribution<input value="NOVAOS system image" disabled></label></div><div class="novaos-lock-note">◈ <span>NOVAOS is locked to its own distribution. It cannot be published as Windows, macOS or Linux.</span></div></div>
<div class="novaos-form-section"><div class="novaos-form-section-title"><span>SYSTEM IMAGE</span><strong>Upload the official build</strong></div><label>ISO / system image <span class="hint">Maximum 4 GB; actual PHP/cPanel upload limits may be lower.</span><input class="file-drop novaos-file" type="file" name="package" accept=".iso,.img,.raw,.zip,.xz,.gz" {{ $release->exists?'':'required' }}></label>@if($release->exists && $release->file_name)<div class="current-file"><strong>Current image:</strong> {{ $release->file_name }} · {{ $release->file_size ? number_format($release->file_size/1048576,1).' MB' : 'size unavailable' }} @if($release->sha256)<br><strong>SHA-256:</strong> <code>{{ $release->sha256 }}</code>@endif</div>@endif<div class="novaos-checksum-note"><strong>SHA-256</strong><span>Calculated automatically from the uploaded file. You never need to type the checksum manually.</span></div></div>
<div class="novaos-form-section"><div class="novaos-form-section-title"><span>RELEASE NOTES</span><strong>Tell users what changed</strong></div><label>Release notes<textarea name="notes" placeholder="Kernel updates, hardware support, installer changes, desktop improvements...">{{ old('notes',$release->notes) }}</textarea></label></div>
<label class="check-line"><input type="checkbox" name="is_published" value="1" @checked(old('is_published',$release->is_published))><span>Publish this NOVAOS release immediately</span></label>
<div class="form-actions"><a class="admin-secondary" href="{{ route('admin.novaos.releases.index') }}">Cancel</a><button class="admin-primary" type="submit">{{ $release->exists?'Save NOVAOS release':'Upload & publish' }}</button></div>
</form>
@endsection
