@extends('admin.layout')
@section('content')
<div class="admin-page-head"><div><span>NOVAOS · RELEASE ARCHIVE</span><h2>Operating-system builds</h2><p>Every NOVAOS build is independent from Windows, macOS and Linux application releases.</p></div><a class="admin-primary" href="{{ route('admin.novaos.releases.create') }}">+ Create NOVAOS release</a></div>
<form class="filter-form" method="GET"><select name="channel"><option value="">All channels</option>@foreach(['Stable','Beta','Nightly'] as $channel)<option value="{{ $channel }}" @selected(request('channel')===$channel)>{{ $channel }}</option>@endforeach</select><select name="architecture"><option value="">All architectures</option>@foreach(['x64','ARM64'] as $arch)<option value="{{ $arch }}" @selected(request('architecture')===$arch)>{{ $arch }}</option>@endforeach</select><button class="admin-secondary">Filter</button></form>
<div class="admin-card table-card"><table><thead><tr><th>Version</th><th>Build</th><th>Package</th><th>Channel</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@forelse($releases as $release)
<tr><td><strong>NOVAOS {{ $release->version }}</strong><small>{{ $release->major_version }} @if($release->codename) · {{ $release->codename }} @endif</small></td><td>{{ $release->build_number }}<small>{{ $release->architecture }}</small></td><td>{{ $release->file_name ?: 'No package' }}<small>{{ $release->file_size ? number_format($release->file_size/1048576,1).' MB' : '—' }}</small></td><td><span class="novaos-channel channel-{{ strtolower($release->channel) }}">{{ $release->channel }}</span></td><td><span class="status {{ $release->is_published?'published':'draft' }}">{{ $release->is_published?'Published':'Draft' }}</span><small>{{ $release->sha256 ? 'SHA-256 calculated' : 'No checksum' }}</small></td><td class="row-actions"><a href="{{ route('admin.novaos.releases.edit',$release) }}">Edit</a><form method="POST" action="{{ route('admin.novaos.releases.toggle',$release) }}">@csrf<button>{{ $release->is_published?'Unpublish':'Publish' }}</button></form><form method="POST" action="{{ route('admin.novaos.releases.destroy',$release) }}" onsubmit="return confirm('Delete this NOVAOS release and its system image?')">@csrf @method('DELETE')<button>Delete</button></form></td></tr>
@empty<tr><td colspan="6" class="admin-empty">No NOVAOS releases found.</td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $releases->links() }}</div>
@endsection
