<?php
namespace App\Services;
use App\Models\{GithubContributor,GithubIssue,GithubPullRequest,GithubRelease,GithubRepository,SoftwareProject};
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;
use RuntimeException;
class GithubService {
 public function client():PendingRequest { $req=Http::acceptJson()->timeout((int)config('github.timeout',15))->retry(2,250); if($token=config('github.token')) $req=$req->withToken($token); return $req; }
 public function parseRepositoryUrl(?string $url):?array { if(!$url)return null; $p=parse_url(trim($url)); if(($p['host']??'')!=='github.com')return null; $parts=array_values(array_filter(explode('/',trim($p['path']??'','/')))); if(count($parts)<2)return null; return ['owner'=>$parts[0],'name'=>preg_replace('/\\.git$/','',$parts[1])]; }
 public function repository(SoftwareProject $project):?GithubRepository { $repo=$this->parseRepositoryUrl($project->github_url); if(!$repo)return null; return GithubRepository::where('software_project_id',$project->id)->first() ?: $this->sync($project); }
 public function sync(SoftwareProject $project):GithubRepository { $parts=$this->parseRepositoryUrl($project->github_url); if(!$parts) throw new RuntimeException('This project does not have a valid GitHub repository URL.'); $base="repos/{$parts['owner']}/{$parts['name']}"; $r=$this->get($base); $data=$r->json(); if(!is_array($data)||empty($data['full_name'])) throw new RuntimeException('GitHub returned an invalid repository response.'); $repo=GithubRepository::updateOrCreate(['software_project_id'=>$project->id],$this->repositoryData($project,$data)); $this->syncContributors($repo,$base); $this->syncIssues($repo,$base); $this->syncPullRequests($repo,$base); $this->syncReleases($repo,$base); $repo->update(['synced_at'=>now()]); return $repo->fresh(); }
 private function get(string $path,array $query=[]){ $res=$this->client()->get('https://api.github.com/'.$path,$query); if($res->failed()) throw new RuntimeException('GitHub API error ('.$res->status().'): '.($res->json('message')?:'Request failed')); return $res; }
 private function repositoryData(SoftwareProject $p,array $d):array{return ['owner'=>$d['owner']['login']??$p->github_url,'name'=>$d['name'],'full_name'=>$d['full_name'],'html_url'=>$d['html_url'],'default_branch'=>$d['default_branch']??null,'description'=>$d['description']??null,'homepage'=>$d['homepage']??null,'license_name'=>$d['license']['name']??null,'stars'=>$d['stargazers_count']??0,'forks'=>$d['forks_count']??0,'open_issues'=>$d['open_issues_count']??0,'watchers'=>$d['subscribers_count']??($d['watchers_count']??0),'language'=>$d['language']??null,'is_fork'=>$d['fork']??false,'is_archived'=>$d['archived']??false,'topics'=>$d['topics']??[],'raw'=>$d];}
 private function syncContributors(GithubRepository $repo,string $base):void { $items=$this->get($base.'/contributors',['per_page'=>100])->json(); foreach(is_array($items)?$items:[] as $d){ if(empty($d['login']))continue; GithubContributor::updateOrCreate(['github_repository_id'=>$repo->id,'login'=>$d['login']],['avatar_url'=>$d['avatar_url']??null,'html_url'=>$d['html_url']??null,'contributions'=>$d['contributions']??0,'raw'=>$d]); } }
 private function syncIssues(GithubRepository $repo,string $base):void { $items=$this->get($base.'/issues',['state'=>'all','per_page'=>100,'sort'=>'updated','direction'=>'desc'])->json(); foreach(is_array($items)?$items:[] as $d){ if(isset($d['pull_request']))continue; GithubIssue::updateOrCreate(['github_repository_id'=>$repo->id,'github_id'=>$d['id']],['number'=>$d['number'],'title'=>$d['title'],'state'=>$d['state'],'author_login'=>$d['user']['login']??null,'html_url'=>$d['html_url'],'opened_at'=>$d['created_at']??null,'updated_at_github'=>$d['updated_at']??null,'raw'=>$d]); } }
 private function syncPullRequests(GithubRepository $repo,string $base):void { $items=$this->get($base.'/pulls',['state'=>'all','per_page'=>100,'sort'=>'updated','direction'=>'desc'])->json(); foreach(is_array($items)?$items:[] as $d){ GithubPullRequest::updateOrCreate(['github_repository_id'=>$repo->id,'github_id'=>$d['id']],['number'=>$d['number'],'title'=>$d['title'],'state'=>$d['state'],'author_login'=>$d['user']['login']??null,'html_url'=>$d['html_url'],'merged'=>!empty($d['merged_at']),'opened_at'=>$d['created_at']??null,'updated_at_github'=>$d['updated_at']??null,'raw'=>$d]); } }
 private function syncReleases(GithubRepository $repo,string $base):void { $items=$this->get($base.'/releases',['per_page'=>100])->json(); foreach(is_array($items)?$items:[] as $d){ GithubRelease::updateOrCreate(['github_repository_id'=>$repo->id,'github_id'=>$d['id']],['tag_name'=>$d['tag_name'],'name'=>$d['name']??null,'body'=>$d['body']??null,'html_url'=>$d['html_url'],'prerelease'=>$d['prerelease']??false,'draft'=>$d['draft']??false,'published_at_github'=>$d['published_at']??null,'assets'=>$d['assets']??[],'raw'=>$d]); } }
 public function webhookValid(string $payload,?string $signature):bool { $secret=config('github.webhook_secret'); if(!$secret || !$signature || !Str::startsWith($signature,'sha256=')) return false; $expected='sha256='.hash_hmac('sha256',$payload,$secret); return hash_equals($expected,$signature); }
 public function handleWebhook(string $event,array $payload):?SoftwareProject { $url=$payload['repository']['html_url']??null; $repo=$this->parseRepositoryUrl($url); if(!$repo)return null; $project=SoftwareProject::where('github_url','https://github.com/'.$repo['owner'].'/'.$repo['name'])->first(); if(!$project) $project=SoftwareProject::where('github_url','https://github.com/'.$repo['owner'].'/'.$repo['name'].'/')->first(); if(!$project)return null; if(in_array($event,['push','release','issues','pull_request','repository'],true)){ try{$this->sync($project);}catch(\Throwable $e){report($e);} } return $project; }
 public function getDocumentationFile(string $owner,string $repo,string $path,string $branch=''):array { $q=$branch?['ref'=>$branch]:[]; $res=$this->get("repos/$owner/$repo/contents/".ltrim($path,'/'),$q); return $res->json(); }
 public function updateDocumentationFile(string $owner,string $repo,string $path,string $message,string $content,string $sha,?string $branch=null):array { if(!config('github.token')) throw new RuntimeException('GitHub write access is not configured on RozeHub. Set GITHUB_TOKEN first.'); $body=['message'=>$message,'content'=>base64_encode($content),'sha'=>$sha]; if($branch)$body['branch']=$branch; $res=$this->client()->put("https://api.github.com/repos/$owner/$repo/contents/".ltrim($path,'/'),$body); if($res->failed()) throw new RuntimeException('GitHub update failed ('.$res->status().'): '.($res->json('message')?:'Request failed')); return $res->json(); }
}
