<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\MarketplaceItem;
use App\Models\MarketplaceRelease;
use App\Models\SoftwareProject;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;
use App\Services\MarketplaceService;
class MarketplaceController extends Controller {
 public function __construct(private readonly MarketplaceService $marketplace) {}
 public function index(Request $request,string $project){$p=SoftwareProject::with(['ecosystemProfile','marketplaceCategories'])->where('slug',$project)->firstOrFail(); $profile=$p->ecosystemProfile; abort_unless($profile?->marketplace_enabled,404); $d=$request->validate(['type'=>'nullable|string|max:60','category'=>'nullable|string|max:100','platform'=>'nullable|string|max:30','architecture'=>'nullable|string|max:20','channel'=>'nullable|string|max:30','appVersion'=>'nullable|string|max:80','sort'=>'nullable|in:name,downloads,rating']); foreach([['type','item_types'],['platform','platforms'],['architecture','architectures'],['channel','channels']] as [$f,$src]) if(isset($d[$f])&&($profile->{$src}??[])&&!in_array($d[$f],$profile->{$src},true)) throw ValidationException::withMessages([$f=>"Unsupported {$f} for {$p->name}."]); $key='rh:mkt:v3:'.sha1(json_encode([$project,$d])); $items=Cache::remember($key,now()->addSeconds(30),fn()=>MarketplaceItem::with(['releases'=>fn($q)=>$q->where('is_published',true)->when(isset($d['platform']),fn($r)=>$r->whereIn('platform',['All',$d['platform']]))->when(isset($d['architecture']),fn($r)=>$r->whereIn('architecture',['All',$d['architecture']]))->when(isset($d['channel']),fn($r)=>$r->where('channel',$d['channel']))->latest('published_at'),'owner.publisherProfile','marketplaceReviews'])->where('is_published',true)->where('software_project_id',$p->id)->when(isset($d['type']),fn($q)=>$q->where('item_type',$d['type']))->when(isset($d['category']),fn($q)=>$q->where('category',$d['category']))->orderByDesc('is_official')->orderBy('name')->get()); return response()->json(['project'=>$project,'ecosystem'=>$this->ecosystem($profile),'categories'=>$p->marketplaceCategories->where('is_active',true)->values(),'filters'=>['types'=>$profile->item_types??[],'platforms'=>$profile->platforms??[],'architectures'=>$profile->architectures??[],'channels'=>$profile->channels??[],'packageTypes'=>$profile->package_types??[]],'count'=>$items->count(),'items'=>$items->map(fn($i)=>$this->itemPayload($i,true))->values(),'checkedAt'=>now()->toIso8601String()]);}
 public function item(string $project,MarketplaceItem $item){abort_unless($item->is_published&&$item->project?->slug===$project,404); $item->load(['project.ecosystemProfile','owner.publisherProfile','marketplaceReviews'=>fn($q)=>$q->where('is_approved',true)->with('user')->latest(),'releases'=>fn($q)=>$q->where('is_published',true)->latest('published_at')]); return response()->json(['project'=>$project,'ecosystem'=>$this->ecosystem($item->project->ecosystemProfile),'item'=>$this->itemPayload($item,true),'rating'=>app(MarketplaceService::class)->ratingSummary($item)]);}
 public function download(MarketplaceRelease $release){abort_unless($release->is_published&&$release->item?->is_published&&$release->file_path,404); abort_unless(Storage::disk('releases')->exists($release->file_path),404); $release->increment('downloads_count');$release->item()->increment('downloads_count');return Storage::disk('releases')->download($release->file_path,$release->file_name,['Content-Type'=>'application/octet-stream','X-RozeHub-Plugin'=>(string)$release->item?->item_id,'X-RozeHub-Version'=>$release->version,'X-RozeHub-SHA256'=>(string)$release->sha256,'Cache-Control'=>'public, max-age=3600']);}
 private function ecosystem($p){return $p?['type'=>$p->ecosystem_type,'title'=>$p->title,'description'=>$p->description,'itemTypes'=>$p->item_types??[],'capabilities'=>$p->capabilities??[],'packageTypes'=>$p->package_types??[],'platforms'=>$p->platforms??[],'architectures'=>$p->architectures??[],'channels'=>$p->channels??[],'integrations'=>$p->integration_targets??[]]:null;}
 private function itemPayload($i,$with=false){$latest=$i->releases->first();$base=['id'=>$i->item_id,'name'=>$i->name,'slug'=>$i->slug,'type'=>$i->item_type,'vendor'=>$i->vendor,'category'=>$i->category,'summary'=>$i->summary,'description'=>$i->description,'license'=>$i->license,'website'=>$i->website,'supportUrl'=>$i->support_url,'repositoryUrl'=>$i->repository_url,'permissions'=>$i->permissions??[],'capabilities'=>$i->capabilities??[],'compatibility'=>$i->compatibility??[],'manifest'=>$i->manifest,'publisher'=>$i->owner?->publisherProfile?->only(['display_name','slug','avatar_url','website','github_url','bio','is_verified']),'official'=>(bool)$i->is_official,'verified'=>(bool)$i->is_verified,'downloads'=>(int)$i->downloads_count,'rating'=>$this->marketplace->ratingSummary($i),'latest'=>$latest?$this->release($latest):null]; if($with)$base['releases']=$i->releases->map(fn($r)=>$this->release($r))->values();return $base;}
 private function release($r){return ['id'=>$r->id,'version'=>$r->version,'platform'=>$r->platform,'architecture'=>$r->architecture,'channel'=>$r->channel,'minimumAppVersion'=>$r->minimum_app_version,'maximumAppVersion'=>$r->maximum_app_version,'packageType'=>$r->package_type,'packageFormat'=>$r->package_format,'fileName'=>$r->file_name,'fileSize'=>$r->file_size,'sha256'=>$r->sha256,'manifest'=>$r->manifest,'dependencies'=>$r->dependencies??[],'mandatory'=>(bool)$r->is_mandatory,'downloadUrl'=>route('api.marketplace.download',$r),'releaseNotes'=>$r->release_notes,'publishedAt'=>optional($r->published_at)->toIso8601String()];}
}
