@extends('developer.layout',['title'=>'Developer Center · RozeHub'])
@section('content')
<div class="dev-hero"><div><span class="eyebrow">DEVELOPER MARKETPLACE</span><h1>Build once. Publish safely.</h1><p>Create plugins and extensions for <strong>Lumina</strong> and <strong>DBNavigator</strong>. Every release goes through an approval and risk-review workflow before it becomes public.</p></div><a class="dev-primary" href="{{ route('developer.marketplace.create') }}">+ Create plugin / extension</a></div>
<div class="dev-stat-grid"><div><small>My items</small><strong>{{ $items->count() }}</strong></div><div><small>Submissions</small><strong>{{ $submissions->total() }}</strong></div><div><small>In review</small><strong>{{ $submissions->whereIn('status',['SUBMITTED','UNDER_REVIEW'])->count() }}</strong></div><div><small>Unread</small><strong>{{ $unread }}</strong></div></div>
<div class="dev-section-head"><div><span class="eyebrow">MY MARKETPLACE ITEMS</span><h2>Your plugins & extensions</h2></div></div>
<div class="dev-grid">@forelse($items as $item)<article class="dev-card"><div class="dev-card-top"><span class="dev-badge {{ $item->item_type }}">{{ ucfirst($item->item_type) }}</span><span>{{ $item->project->name }}</span></div><h3>{{ $item->name }}</h3><p>{{ $item->summary ?: 'No summary yet.' }}</p><div class="dev-card-actions"><a href="{{ route('developer.marketplace.releases.create',$item) }}">New release</a><a href="{{ route('developer.marketplace.edit',$item) }}">Edit</a></div></article>@empty<div class="dev-empty">You have not created a marketplace item yet.</div>@endforelse</div>
<div class="dev-section-head"><div><span class="eyebrow">RECENT SUBMISSIONS</span><h2>Review status</h2></div><a href="{{ route('developer.marketplace.submissions') }}">View all →</a></div>
<div class="dev-table"><table><thead><tr><th>Item</th><th>Version</th><th>Status</th><th>Risk</th><th>Submitted</th></tr></thead><tbody>@forelse($submissions as $s)<tr><td><a href="{{ route('developer.marketplace.submission',$s) }}">{{ $s->item->name }}</a></td><td>{{ $s->release?->version ?? '—' }}</td><td><span class="status-pill status-{{ strtolower($s->status) }}">{{ str_replace('_',' ',$s->status) }}</span></td><td><span class="risk-pill risk-{{ strtolower($s->risk_level) }}">{{ $s->risk_level }} · {{ $s->risk_score }}</span></td><td>{{ optional($s->submitted_at)->diffForHumans() ?? 'Draft' }}</td></tr>@empty<tr><td colspan="5">No submissions yet.</td></tr>@endforelse</tbody></table></div>
@endsection
