@extends('admin.layout')
@section('content')
<div class="admin-page-head"><div><span class="admin-kicker">GITHUB ECOSYSTEM</span><h2>{{ $project->name }}</h2><p>Repository intelligence, community activity and release history.</p></div><div style="display:flex;gap:8px"><a class="admin-secondary" href="{{ route('admin.projects.edit',$project) }}">Project settings</a><form method="POST" action="{{ route('admin.github.sync',$project) }}">@csrf<button class="admin-primary">Sync GitHub</button></form></div></div>
@if(!$project->github_url)<div class="admin-alert error">No GitHub repository is configured for this project.</div>@else
<div class="admin-card"><div style="display:flex;justify-content:space-between;gap:20px"><div><strong>{{ $repo?->full_name ?: $project->github_url }}</strong><p>{{ $repo?->description }}</p></div><a class="admin-secondary" href="{{ $project->github_url }}" target="_blank" rel="noopener">Open GitHub ↗</a></div>@if($repo)<div class="form-grid four" style="margin-top:18px"><div><small>Stars</small><strong>{{ number_format($repo->stars) }}</strong></div><div><small>Forks</small><strong>{{ number_format($repo->forks) }}</strong></div><div><small>Open issues</small><strong>{{ number_format($repo->open_issues) }}</strong></div><div><small>Language</small><strong>{{ $repo->language ?: '—' }}</strong></div></div><p class="muted">Last synchronized {{ $repo->synced_at?->diffForHumans() ?: 'never' }} · default branch {{ $repo->default_branch ?: '—' }}</p>@endif</div>
@if($repo)<div class="form-grid two"><div class="admin-card"><h3>Contributors</h3>@forelse($repo->contributors as $c)<div style="display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #e7ece9"><a href="{{ $c->html_url }}" target="_blank">{{ $c->login }}</a><strong>{{ number_format($c->contributions) }}</strong></div>@empty<p class="muted">No contributor data yet.</p>@endforelse</div><div class="admin-card"><h3>Latest releases</h3>@forelse($repo->releases as $r)<div style="padding:9px 0;border-bottom:1px solid #e7ece9"><a href="{{ $r->html_url }}" target="_blank"><strong>{{ $r->tag_name }}</strong></a><span class="muted"> · {{ $r->published_at_github?->format('Y-m-d') ?: 'unpublished' }}</span><p>{{ $r->name }}</p></div>@empty<p class="muted">No releases.</p>@endforelse</div></div>
<div class="form-grid two"><div class="admin-card"><h3>Open issues</h3>@forelse($repo->issues->where('state','open') as $i)<div style="padding:9px 0;border-bottom:1px solid #e7ece9"><a href="{{ $i->html_url }}" target="_blank">#{{ $i->number }} · {{ $i->title }}</a><small class="muted"> by {{ $i->author_login ?: 'unknown' }}</small></div>@empty<p class="muted">No open issues.</p>@endforelse</div><div class="admin-card"><h3>Pull requests</h3>@forelse($repo->pullRequests->where('state','open') as $pr)<div style="padding:9px 0;border-bottom:1px solid #e7ece9"><a href="{{ $pr->html_url }}" target="_blank">#{{ $pr->number }} · {{ $pr->title }}</a><small class="muted"> by {{ $pr->author_login ?: 'unknown' }}</small></div>@empty<p class="muted">No open pull requests.</p>@endforelse</div></div>
<div class="admin-card"><h3>Documentation</h3><p>Edit repository documentation directly through GitHub's Contents API. Every edit creates a normal Git commit.</p><a class="admin-primary" href="{{ route('admin.github.documentation',$project) }}">Edit documentation on GitHub</a></div>
@endif @endif
@endsection
