<?php $__env->startSection('content'); ?>
<div class="admin-page-head"><div><span>SOFTWARE</span><h2><?php echo e($mode === 'create' ? 'Add a new product' : 'Edit '.$project->name); ?></h2><p>These details appear across the public catalog.</p></div><a class="admin-secondary" href="<?php echo e(route('admin.projects.index')); ?>">← Back</a></div>
<form class="admin-form-card" method="POST" action="<?php echo e($mode==='create'?route('admin.projects.store'):route('admin.projects.update',$project)); ?>"><?php echo csrf_field(); ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($mode==='edit'): ?><?php echo method_field('PUT'); ?><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<div class="form-grid two"><label>Name<input name="name" value="<?php echo e(old('name',$project->name)); ?>" required></label><label>Slug<input name="slug" value="<?php echo e(old('slug',$project->slug)); ?>" placeholder="auto-generated if blank"></label></div>
<label>Tagline<input name="tagline" value="<?php echo e(old('tagline',$project->tagline)); ?>" required></label><label>Description<textarea name="description" required><?php echo e(old('description',$project->description)); ?></textarea></label>
<div class="form-grid three"><label>Category<input name="category" value="<?php echo e(old('category',$project->category)); ?>" required></label><label>Icon<input name="icon" value="<?php echo e(old('icon',$project->icon ?: 'R')); ?>" maxlength="8" required></label><label>Accent<select name="accent"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['mint','coral','lilac','gold','blue']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $accent): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option <?php echo e(old('accent',$project->accent)===$accent?'selected':''); ?>><?php echo e($accent); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label></div>
<label>Website URL<input type="url" name="website" value="<?php echo e(old('website',$project->website)); ?>" placeholder="https://..."></label><div class="form-actions"><a class="admin-secondary" href="<?php echo e(route('admin.projects.index')); ?>">Cancel</a><button class="admin-primary" type="submit"><?php echo e($mode==='create'?'Create software':'Save changes'); ?></button></div>
</form>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.layout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /home/firoze/Downloads/RozeHub-rich-documentation-editor-format-state-fixed/RozeHub-final/resources/views/admin/projects/form.blade.php ENDPATH**/ ?>