<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Documentation · RozeHub</title><link rel="icon" href="<?php echo e(asset('images/rozehub-icon.png')); ?>"><link rel="stylesheet" href="<?php echo e(asset('css/rozehub.css')); ?>">
</head><body class="docs-body">
<header class="docs-topbar"><div class="docs-topbar-inner"><a class="docs-brand" href="<?php echo e(route('hub')); ?>"><span class="docs-brand-mark"><img src="<?php echo e(asset('images/rozehub-icon.png')); ?>" alt="RozeHub"></span><span><strong>RozeHub</strong><small>Documentation</small></span></a><nav><a href="<?php echo e(route('hub')); ?>">Home</a><a class="active" href="<?php echo e(route('docs.index')); ?>">Docs</a><a href="<?php echo e(route('hub')); ?>#releases">Releases</a></nav><form class="docs-search" action="<?php echo e(route('docs.search')); ?>"><span>⌕</span><input name="q" placeholder="Search documentation…" value=""></form></div></header>
<main class="docs-wrap">
<section class="docs-landing-hero"><div><span class="docs-kicker">ROZEHUB DOCUMENTATION</span><h1>Build. Learn. Understand.</h1><p>Versioned documentation for every project in the RozeHub ecosystem — from developer tools to NOVAOS, the Roze programming language, and StratosDB.</p><div class="docs-hero-actions"><a class="docs-primary" href="#projects">Browse documentation <span>↓</span></a><a class="docs-secondary" href="<?php echo e(route('docs.search')); ?>">Search docs →</a></div></div><div class="docs-hero-orbit"><div class="orbit-core">R</div><span class="orbit-pill one">NOVAOS</span><span class="orbit-pill two">Roze</span><span class="orbit-pill three">StratosDB</span><span class="orbit-pill four">Tools</span></div></section>
<section id="projects" class="docs-projects"><div class="docs-section-heading"><div><span class="docs-kicker">DOCUMENTATION LIBRARY</span><h2>Choose a project.</h2></div><p>Each project has its own navigation, guides, reference material, release notes, and printable documentation.</p></div>
<div class="docs-project-grid">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
<article class="docs-project-card <?php echo e(in_array($project->slug,['novaos','roze-language','stratosdb']) ? 'docs-special' : ''); ?>">
<div class="docs-project-card-top"><span class="docs-project-icon accent-<?php echo e($project->accent); ?>"><?php echo e($project->icon); ?></span><span><?php echo e($project->category); ?></span></div>
<h3><?php echo e($project->name); ?></h3><p><?php echo e($project->tagline); ?></p>
<div class="docs-project-meta"><span><?php echo e($project->published_docs_count); ?> published pages</span><span><?php echo e($project->documentationSections->count()); ?> sections</span><span><?php echo e(optional($project->releases->first())->version ? 'v'.optional($project->releases->first())->version : 'docs current'); ?></span></div>
<div class="docs-card-actions"><a href="<?php echo e(route('docs.project',$project)); ?>">Open docs <span>→</span></a><a class="quiet" href="<?php echo e(route('docs.print',$project)); ?>">Print / PDF</a></div>
</article>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
</div></section>
</main>
<footer class="docs-footer"><span>RozeHub Documentation</span><span>Laravel · PHP · No Node.js required</span></footer>
</body></html>
<?php /**PATH /home/firoze/Downloads/RozeHub-documentation-size-controls-migration-fixed/RozeHub-final/resources/views/docs/index.blade.php ENDPATH**/ ?>