<?php $__env->startSection('content'); ?>
<div class="admin-page-head"><div><p class="admin-kicker">Project ecosystem</p><h2>Marketplace policies</h2><p class="muted">Configure what each RozeHub project can publish. No project-specific rules are stored in controller code.</p></div></div>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Project</th><th>Ecosystem</th><th>Marketplace</th><th>Community</th><th>Item types</th><th></th></tr></thead><tbody>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?> <?php ($p=$project->ecosystemProfile); ?>
<tr><td><strong><?php echo e($project->name); ?></strong><div class="muted"><?php echo e($project->category); ?></div></td><td><?php echo e($p?->title ?? 'Not configured'); ?></td><td><?php echo e($p?->marketplace_enabled ? 'Enabled' : 'Disabled'); ?></td><td><?php echo e($p?->community_contributions ? 'Enabled' : 'Disabled'); ?></td><td><?php echo e(implode(', ', $p?->item_types ?? []) ?: '—'); ?></td><td><a class="admin-secondary" href="<?php echo e(route('admin.ecosystem.edit',$project)); ?>">Configure</a></td></tr>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
</tbody></table></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.layout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /home/firoze/Downloads/RozeHub-Phase4-Release-Platform/resources/views/admin/ecosystem/index.blade.php ENDPATH**/ ?>