<?php $__env->startSection('content'); ?>
<div class="admin-page-head"><div><p class="admin-kicker"><?php echo e($project->name); ?></p><h2>Ecosystem policy</h2><p class="muted">These values are the source of truth for developer forms, marketplace validation and API metadata.</p></div></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session('success')): ?><div class="admin-alert success"><?php echo e(session('success')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="admin-alert error"><ul><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $e): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><li><?php echo e($e); ?></li><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></ul></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<form method="POST" action="<?php echo e(route('admin.ecosystem.update',$project)); ?>" class="admin-form"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?>
<label>Ecosystem type<input name="ecosystem_type" value="<?php echo e(old('ecosystem_type',$profile->ecosystem_type)); ?>" required></label>
<label>Title<input name="title" value="<?php echo e(old('title',$profile->title)); ?>" required></label>
<label>Description<textarea name="description" rows="4"><?php echo e(old('description',$profile->description)); ?></textarea></label>
<?php ($lists=['item_types'=>'Item types','capabilities'=>'Capabilities','package_types'=>'Package types','platforms'=>'Platforms','architectures'=>'Architectures','channels'=>'Channels','integration_targets'=>'Integration targets']); ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $lists; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><label><?php echo e($label); ?><textarea name="<?php echo e($key); ?>[]" rows="4" placeholder="One value per line"><?php echo e(implode("\n", old($key,$profile->{$key} ?? []))); ?></textarea></label><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
<div class="checkbox-row"><label><input type="checkbox" name="marketplace_enabled" value="1" <?php if(old('marketplace_enabled',$profile->marketplace_enabled)): echo 'checked'; endif; ?>> Marketplace enabled</label><label><input type="checkbox" name="community_contributions" value="1" <?php if(old('community_contributions',$profile->community_contributions)): echo 'checked'; endif; ?>> Community contributions enabled</label><label><input type="checkbox" name="moderation_required" value="1" <?php if(old('moderation_required',$profile->moderation_required)): echo 'checked'; endif; ?>> Moderation required</label></div>
<button class="admin-primary">Save ecosystem policy</button> <a class="admin-secondary" href="<?php echo e(route('admin.ecosystem.index')); ?>">Back</a>
</form>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.layout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /home/firoze/projects/others/RozeHub/resources/views/admin/ecosystem/form.blade.php ENDPATH**/ ?>