<?php $__env->startSection('content'); ?>
<div class="admin-page-head"><div><p class="admin-kicker">Ecosystem marketplace</p><h2><?php echo e($mode === 'create' ? 'New ecosystem item' : $item->name); ?></h2><p class="muted">The selected project controls which extension types, capabilities and integrations are valid.</p></div></div>
<form class="admin-form" method="POST" action="<?php echo e($mode === 'create' ? route('admin.marketplace.store') : route('admin.marketplace.update', $item)); ?>"><?php echo csrf_field(); ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($mode === 'edit'): ?> <?php echo method_field('PUT'); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<div class="form-grid-2">
<label>Project<select name="software_project_id" id="admin-project" required><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($project->id); ?>" <?php if(old('software_project_id',$item->software_project_id)==$project->id): echo 'selected'; endif; ?>><?php echo e($project->name); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
<label>Type<select name="item_type" id="admin-type" required></select></label>
<label>Name<input name="name" required maxlength="160" value="<?php echo e(old('name',$item->name)); ?>"></label><label>Stable Item ID<input name="item_id" required maxlength="160" value="<?php echo e(old('item_id',$item->item_id)); ?>"></label>
<label>URL slug<input name="slug" maxlength="120" value="<?php echo e(old('slug',$item->slug)); ?>"></label><label>Vendor / publisher<input name="vendor" maxlength="160" value="<?php echo e(old('vendor',$item->vendor)); ?>"></label>
<label>Category<input name="category" maxlength="100" value="<?php echo e(old('category',$item->category)); ?>"></label><label>License<select name="license"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['MIT','Apache-2.0','GPL-3.0','BSD-2-Clause','BSD-3-Clause','MPL-2.0','LGPL-3.0','Proprietary']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $license): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($license); ?>" <?php if(old('license',$item->license)===$license): echo 'selected'; endif; ?>><?php echo e($license); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
<label>Website<input type="url" name="website" value="<?php echo e(old('website',$item->website)); ?>"></label><label>Repository<input type="url" name="repository_url" value="<?php echo e(old('repository_url',$item->repository_url)); ?>"></label><label>Support URL<input type="url" name="support_url" value="<?php echo e(old('support_url',$item->support_url)); ?>"></label><label>Icon path<input name="icon_path" value="<?php echo e(old('icon_path',$item->icon_path)); ?>"></label>
</div>
<label>Short summary<textarea name="summary" maxlength="500" rows="2"><?php echo e(old('summary',$item->summary)); ?></textarea></label><label>Description<textarea name="description" rows="8"><?php echo e(old('description',$item->description)); ?></textarea></label>
<div class="ecosystem-grid"><section class="market-permission-box"><h3>Capabilities</h3><p class="muted" id="admin-capability-help"></p><div id="admin-capability-chips" class="chip-list"></div><textarea name="capabilities_text" rows="5"><?php echo e(old('capabilities_text',implode("\n",$item->capabilities??[]))); ?></textarea></section><section class="market-permission-box"><h3>Compatibility & integrations</h3><div id="admin-integration-chips" class="chip-list"></div><textarea name="compatibility_text" rows="5"><?php echo e(old('compatibility_text',implode("\n",$item->compatibility['targets']??[]))); ?></textarea><input name="minimum_project_version" value="<?php echo e(old('minimum_project_version',$item->compatibility['minimumProjectVersion']??'')); ?>" placeholder="Minimum project version"></section></div>
<div class="check-row"><label><input type="checkbox" name="is_official" value="1" <?php if(old('is_official',$item->is_official)): echo 'checked'; endif; ?>> Official</label><label><input type="checkbox" name="is_verified" value="1" <?php if(old('is_verified',$item->is_verified)): echo 'checked'; endif; ?>> Verified publisher</label><label><input type="checkbox" name="is_published" value="1" <?php if(old('is_published',$item->is_published)): echo 'checked'; endif; ?>> Publish</label></div>
<div class="form-actions"><a class="admin-button" href="<?php echo e(route('admin.marketplace.index')); ?>">Cancel</a><button class="admin-button primary"><?php echo e($mode === 'create' ? 'Create item' : 'Save changes'); ?></button></div></form>
<script>
const adminEcosystems=<?php echo json_encode($projects->mapWithKeys(fn($p)=>[$p->id=>['types'=>$p->ecosystemProfile?->item_types??[], 'capabilities'=>$p->ecosystemProfile?->capabilities??[], 'integrations'=>$p->ecosystemProfile?->integration_targets??[]]])) ?>;
const adminSelectedType=<?php echo json_encode(old('item_type', $item->item_type), 512) ?>;const ap=document.getElementById('admin-project'),at=document.getElementById('admin-type');
function adminRender(){const e=adminEcosystems[ap.value]||{types:[],capabilities:[],integrations:[]};at.innerHTML=e.types.map(x=>`<option value="${x}">${x.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase())}</option>`).join('');if(!at.dataset.changed&&e.types.includes(adminSelectedType))at.value=adminSelectedType;document.getElementById('admin-capability-chips').innerHTML=e.capabilities.map(x=>`<button type="button" class="chip" onclick="adminAdd('capabilities_text','${x}')">${x}</button>`).join('');document.getElementById('admin-integration-chips').innerHTML=e.integrations.map(x=>`<button type="button" class="chip" onclick="adminAdd('compatibility_text','${x}')">${x}</button>`).join('');}
function adminAdd(name,v){const el=document.querySelector(`[name="${name}"]`);let a=el.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!a.includes(v))a.push(v);el.value=a.join('\n');}ap.addEventListener('change',()=>{at.dataset.changed='1';adminRender()});adminRender();
</script>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.layout', ['heading' => $mode === 'create' ? 'Create marketplace item' : 'Edit marketplace item'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /home/firoze/Downloads/RozeHub-Ecosystem-Extensions-Full-Updated/RozeHub-Ecosystem-Extensions-Updated/resources/views/admin/marketplace/item-form.blade.php ENDPATH**/ ?>