<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $project->name }} Documentation · RozeHub</title><link rel="icon" href="{{ asset('images/rozehub-icon.png') }}"><link rel="stylesheet" href="{{ asset('css/rozehub.css') }}"></head><body class="docs-body">
<header class="docs-topbar"><div class="docs-topbar-inner"><a class="docs-brand" href="{{ route('docs.index') }}"><span class="docs-brand-mark"><img src="{{ asset('images/rozehub-icon.png') }}" alt="RozeHub"></span><span><strong>RozeHub</strong><small>Documentation</small></span></a><nav><a href="{{ route('hub') }}">Home</a><a class="active" href="{{ route('docs.index') }}">Docs</a></nav><form class="docs-search" action="{{ route('docs.search') }}"><span>⌕</span><input name="q" placeholder="Search documentation…"></form></div></header>
<div class="docs-product-bar"><div><span class="docs-kicker">{{ $project->category }}</span><h1>{{ $project->name }}</h1><p>{{ $project->description }}</p></div><div class="docs-product-actions"><form class="docs-version-picker" method="GET" action="{{ route('docs.project',$project) }}"><label for="docs-release">Documentation version</label><select id="docs-release" name="release" onchange="this.form.submit()"><option value="">Latest release</option>@foreach($project->releases as $release)<option value="{{ $release->id }}" {{ $selectedRelease?->id === $release->id ? 'selected':'' }}>v{{ $release->version }} · {{ ucfirst($release->channel ?: 'release') }}</option>@endforeach</select></form>@if($project->github_url)<a class="docs-github-link" href="{{ $project->github_url }}" target="_blank" rel="noopener">GitHub ↗</a>@endif@if($project->github_url)<a href="{{ route('github.contribute',$project) }}">Contribute ↗</a>@endif<a href="{{ route('docs.print',$project) }}{{ $selectedRelease ? '?release='.$selectedRelease->id : '' }}">Print / Save PDF</a><a href="{{ route('docs.markdown',$project) }}{{ $selectedRelease ? '?release='.$selectedRelease->id : '' }}">Download Markdown</a></div></div>
<main class="docs-layout"><aside class="docs-sidebar"><a class="docs-side-home" href="{{ route('docs.index') }}">← All documentation</a><div class="docs-version">{{ $selectedRelease ? 'VERSIONED DOCUMENTATION · V'.$selectedRelease->version : 'ALL VERSION DOCUMENTATION' }}</div>@foreach($project->documentationSections as $section)<div class="docs-side-section"><div class="docs-side-section-title"><span>{{ $section->icon }}</span>{{ $section->title }}</div>@foreach($section->pages as $item)<a href="{{ route('docs.page',[$project,$item->slug]) }}{{ $item->release_id ? '?release='.$item->release_id : ($selectedRelease ? '?release='.$selectedRelease->id : '') }}">{{ $item->title }}@if($item->release)<small class="docs-side-version">v{{ $item->release->version }}</small>@endif</a>@endforeach</div>@endforeach</aside>
<section class="docs-main"><div class="docs-breadcrumb"><a href="{{ route('docs.index') }}">Docs</a><span>/</span><strong>{{ $project->name }}</strong>@if($selectedRelease)<span>/</span><strong>v{{ $selectedRelease->version }}</strong>@endif</div><div class="docs-project-intro"><div><span class="docs-kicker">DOCUMENTATION HOME</span><h2>Everything you need to build with {{ $project->name }}.</h2><p>{{ $project->tagline }}</p></div><div class="docs-project-badge"><strong>{{ $project->documentationSections->sum(fn($section) => $section->pages->count()) }}</strong><span>visible pages</span>@if($selectedRelease)<small>Release · v{{ $selectedRelease->version }}</small>@else<small>All releases</small>@endif</div></div>
<div class="docs-version-banner"><div><span>DOCUMENTATION SCOPE</span><strong>{{ $selectedRelease ? 'v'.$selectedRelease->version : 'All releases' }}</strong><p>{{ $selectedRelease ? 'Release-specific pages plus general documentation are shown.' : 'Only general documentation is shown. Select a release for version-specific content.' }}</p></div><div class="docs-version-banner-meta">{{ $selectedRelease?->codename ? 'Codename · '.$selectedRelease->codename : 'Version-aware documentation' }}</div></div>
@if($project->github_url)
<div class="docs-open-source-bar"><div><span>OPEN SOURCE</span><strong>Build with {{ $project->name }}</strong><p>Source code, issues, pull requests, and contribution discussions live on GitHub.</p></div><a href="{{ $project->github_url }}" target="_blank" rel="noopener">View repository ↗</a></div>
@endif
<div class="docs-section-list">@foreach($project->documentationSections as $section)<section class="docs-section-card"><div class="docs-section-card-head"><div><span>{{ $section->icon }}</span><h3>{{ $section->title }}</h3></div><p>{{ $section->description }}</p></div><div class="docs-page-grid">@forelse($section->pages as $item)<a href="{{ route('docs.page',[$project,$item->slug]) }}{{ $item->release_id ? '?release='.$item->release_id : ($selectedRelease ? '?release='.$selectedRelease->id : '') }}" class="docs-page-card"><div class="docs-page-tags"><span class="docs-kind">{{ str_replace('-',' ',strtoupper($item->kind)) }}</span>@if($item->release)<span class="docs-page-version">v{{ $item->release->version }}</span>@else<span class="docs-page-version general">ALL</span>@endif</div><h4>{{ $item->title }}</h4><p>{{ $item->summary }}</p><span class="docs-arrow">Read article →</span></a>@empty<div class="docs-empty-section">No published pages are available for this version.</div>@endforelse</div></section>@endforeach</div></section></main>
<footer class="docs-footer"><span>{{ $project->name }} Documentation</span><span><a href="{{ route('docs.print',$project) }}{{ $selectedRelease ? '?release='.$selectedRelease->id : '' }}">Print / PDF</a> · <a href="{{ route('docs.markdown',$project) }}{{ $selectedRelease ? '?release='.$selectedRelease->id : '' }}">Markdown</a></span></footer>
</body></html>
