<main class="studio-shell">
        <header class="topbar"><a class="brand" href="{{ route('hub') }}"><span class="brand-mark">R</span><span>RozeHub</span></a><nav><a href="{{ route('hub') }}">← Back to catalog</a></nav><span class="studio-label">Publisher studio</span></header>
        <section class="studio-hero"><p class="eyebrow">Release management</p><h1>Ship the next version.</h1><p>Upload a package once. RozeHub creates a platform-ready release, displays it in the catalog, and tracks every completed download.</p></section>
        <section class="studio-grid"><form class="publish-form" wire:submit="save"><div class="panel-title"><h2>Publish a release</h2><span>Draft → Live</span></div>@if(session('release-saved'))<p class="success">{{ session('release-saved') }}</p>@endif
            <label>Project<select wire:model="projectId"><option value="">Choose software</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></label>@error('projectId')<small class="error">{{ $message }}</small>@enderror
            <div class="field-pair"><label>Version<input wire:model="version" placeholder="e.g. 1.4.0"></label><label>Channel<select wire:model="channel"><option>Stable</option><option>Beta</option><option>Nightly</option></select></label></div>
            <div class="field-pair"><label>Platform<select wire:model="platform"><option>Windows</option><option>macOS</option><option>Linux</option></select></label><label>Architecture<select wire:model="architecture"><option>x64</option><option>ARM64</option></select></label></div>
            <label>Package file<input class="file-input" wire:model="package" type="file"></label>@error('package')<small class="error">{{ $message }}</small>@enderror
            <label>Release notes<textarea wire:model="notes" placeholder="What changed in this version?"></textarea></label><button class="button primary" type="submit" wire:loading.attr="disabled">Publish package <span>↑</span></button>
        </form>
        <aside class="studio-side"><div class="upload-rules"><p class="eyebrow">Package policy</p><h3>What gets published</h3><p>Each package is stored under its product name and appears in the public catalog as soon as it is published.</p><ul><li>Downloads are counted server-side</li><li>Versions are unique per platform</li><li>Keep release notes concise and useful</li></ul></div><div class="studio-stat"><strong>{{ $releases->sum('downloads_count') }}</strong><span>total recorded downloads</span></div></aside></section>
        <section class="release-history"><div class="panel-title"><h2>Recent releases</h2><span>{{ $releases->count() }} shown</span></div>@forelse($releases as $release)<div class="history-row"><div><strong>{{ $release->project->name }}</strong><p>{{ $release->platform }} · {{ $release->architecture }} · v{{ $release->version }}</p></div><span class="channel">{{ $release->channel }}</span><span>{{ number_format($release->downloads_count) }} downloads</span></div>@empty <p class="empty">Your published releases will appear here.</p>@endforelse</section>
</main>
