@extends('admin.layout')
@section('content')
<div class="admin-actions"><div><span class="eyebrow">PHASE 5</span><h1>Analytics</h1><p class="admin-muted">A single operational view of downloads, marketplace usage, projects, documentation and GitHub activity.</p></div><form method="GET"><select name="days" onchange="this.form.submit()"><option value="7" @selected($days==7)>7 days</option><option value="30" @selected($days==30)>30 days</option><option value="90" @selected($days==90)>90 days</option><option value="365" @selected($days==365)>1 year</option></select></form></div>
<div class="metric-grid"><div class="metric"><span>Events</span><strong>{{ number_format($summary['total_events']) }}</strong><small>tracked activity</small></div><div class="metric"><span>Downloads</span><strong>{{ number_format($summary['downloads']) }}</strong><small>release packages</small></div><div class="metric"><span>Marketplace</span><strong>{{ number_format($summary['marketplace_views']) }}</strong><small>item views</small></div><div class="metric"><span>Documentation</span><strong>{{ number_format($summary['documentation_views']) }}</strong><small>page views</small></div><div class="metric"><span>Visitors</span><strong>{{ number_format($summary['unique_visitors']) }}</strong><small>privacy-preserving estimate</small></div><div class="metric"><span>GitHub</span><strong>{{ number_format($summary['github_activity']) }}</strong><small>sync/webhook activity</small></div></div>
<section class="admin-card"><div class="card-heading"><div><span>TRAFFIC</span><h2>Daily activity</h2></div></div><div style="overflow:auto"><div style="display:flex;align-items:flex-end;gap:6px;height:150px;margin:12px 0 18px;overflow:auto;padding:8px 0">@php($maxDaily=max(1,collect($summary['daily'])->max('events') ?? 1)) @foreach($summary['daily'] as $d)<div title="{{ $d['date'] }}: {{ $d['events'] }} events" style="min-width:12px;height:{{ max(4, round(($d['events']/$maxDaily)*120)) }}px;border-radius:3px 3px 0 0;background:var(--accent,#6b7280)"></div>@endforeach</div><table class="admin-table"><thead><tr><th>Date</th><th>Events</th></tr></thead><tbody>@forelse($summary['daily'] as $d)<tr><td>{{ $d['date'] }}</td><td>{{ number_format($d['events']) }}</td></tr>@empty<tr><td colspan="2">No activity yet.</td></tr>@endforelse</tbody></table></div></section>
<div class="admin-columns"><section class="admin-card"><div class="card-heading"><div><span>PROJECTS</span><h2>Project analytics</h2></div></div><table class="admin-table"><thead><tr><th>Project</th><th>Downloads</th><th>Marketplace</th><th>Docs</th><th>GitHub</th><th></th></tr></thead><tbody>@forelse($projects as $p)<tr><td><strong>{{ $p->name }}</strong></td><td>{{ $p->downloads }}</td><td>{{ $p->marketplace_views }}</td><td>{{ $p->documentation_views }}</td><td>{{ $p->github_activity }}</td><td><a href="{{ route('admin.analytics.project',$p->slug) }}">Details →</a></td></tr>@empty<tr><td colspan="6">No project activity yet.</td></tr>@endforelse</tbody></table></section>
<section class="admin-card"><div class="card-heading"><div><span>RELEASES</span><h2>Top downloads</h2></div></div><table class="admin-table"><thead><tr><th>Project</th><th>Version</th><th>Downloads</th></tr></thead><tbody>@forelse($topDownloads as $d)<tr><td>{{ $d->name }}</td><td>{{ $d->version ? 'v'.$d->version : '—' }}</td><td>{{ $d->downloads }}</td></tr>@empty<tr><td colspan="3">No downloads yet.</td></tr>@endforelse</tbody></table></section></div>
<div class="admin-columns"><section class="admin-card"><div class="card-heading"><div><span>GITHUB</span><h2>Repository health</h2></div></div><table class="admin-table"><thead><tr><th>Project</th><th>Stars</th><th>Forks</th><th>Issues</th><th>Contributors</th><th>PRs</th></tr></thead><tbody>@forelse($github as $g)<tr><td>{{ $g['project'] }}</td><td>{{ $g['stars'] }}</td><td>{{ $g['forks'] }}</td><td>{{ $g['issues'] }}</td><td>{{ $g['contributors'] }}</td><td>{{ $g['pull_requests'] }}</td></tr>@empty<tr><td colspan="6">No GitHub repositories connected.</td></tr>@endforelse</tbody></table></section>
<section class="admin-card"><div class="card-heading"><div><span>DOCUMENTATION</span><h2>Popular pages</h2></div></div><table class="admin-table"><thead><tr><th>Page</th><th>Views</th></tr></thead><tbody>@forelse($docs as $d)<tr><td>{{ $d->page_slug ?: 'Unknown' }}</td><td>{{ $d->views }}</td></tr>@empty<tr><td colspan="2">No documentation views yet.</td></tr>@endforelse</tbody></table></section></div>
<section class="admin-card"><div class="card-heading"><div><span>EVENT STREAM</span><h2>Recent activity</h2></div></div><table class="admin-table"><thead><tr><th>Time</th><th>Event</th><th>Project</th><th>Details</th></tr></thead><tbody>@forelse($recent as $e)<tr><td>{{ $e->created_at?->format('Y-m-d H:i') }}</td><td>{{ str_replace('_',' ',ucwords($e->event_type,'_')) }}</td><td>{{ $e->project?->name ?? 'Platform' }}</td><td>{{ collect($e->metadata ?? [])->map(fn($v,$k)=>$k.': '.$v)->implode(' · ') }}</td></tr>@empty<tr><td colspan="4">No analytics events yet.</td></tr>@endforelse</tbody></table></section>
@endsection
