<?php
namespace App\Http\Controllers;
use App\Models\Release; use App\Models\SoftwareProject; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str; use Illuminate\Validation\Rule;
class AdminReleaseController extends Controller {
 public function index(Request $r){$releases=Release::with('project')->when($r->filled('project'),fn($q)=>$q->where('software_project_id',$r->integer('project')))->when($r->filled('platform'),fn($q)=>$q->where('platform',$r->string('platform')))->latest('created_at')->paginate(15)->withQueryString();return view('admin.releases.index',['releases'=>$releases,'projects'=>SoftwareProject::orderBy('name')->get()]);}
 public function create(){return view('admin.releases.form',['release'=>new Release(['platform'=>'Windows','architecture'=>'x64','channel'=>'Stable']),'projects'=>SoftwareProject::orderBy('name')->get(),'mode'=>'create']);}
 public function store(Request $r){$d=$this->validated($r);$f=$r->file('package');$p=SoftwareProject::findOrFail($d['software_project_id']);$d['file_path']=$f->store('releases/'.Str::slug($p->name),'local');$d['file_name']=$f->getClientOriginalName();$d['file_size']=$f->getSize();$d['is_published']=$r->boolean('is_published');$d['published_at']=$d['is_published']?now():null;Release::create($d);return redirect()->route('admin.releases.index')->with('success','Release uploaded successfully.');}
 public function edit(Release $release){return view('admin.releases.form',['release'=>$release,'projects'=>SoftwareProject::orderBy('name')->get(),'mode'=>'edit']);}
 public function update(Request $r,Release $release){$d=$this->validated($r,$release,false);$d['is_published']=$r->boolean('is_published');$d['published_at']=$d['is_published']?($release->published_at?:now()):null;if($r->hasFile('package')){$f=$r->file('package');$p=SoftwareProject::findOrFail($d['software_project_id']);if($release->file_path&&Storage::disk('local')->exists($release->file_path))Storage::disk('local')->delete($release->file_path);$d['file_path']=$f->store('releases/'.Str::slug($p->name),'local');$d['file_name']=$f->getClientOriginalName();$d['file_size']=$f->getSize();}$release->update($d);return redirect()->route('admin.releases.index')->with('success','Release updated.');}
 public function toggle(Release $release){$release->update(['is_published'=>!$release->is_published,'published_at'=>!$release->is_published?now():null]);return back()->with('success',$release->is_published?'Release published.':'Release unpublished.');}
 public function destroy(Release $release){if($release->file_path&&Storage::disk('local')->exists($release->file_path))Storage::disk('local')->delete($release->file_path);$release->delete();return back()->with('success','Release deleted.');}
 private function validated(Request $r,?Release $release=null,bool $requireFile=true):array{$rules=['software_project_id'=>['required','exists:software_projects,id'],'version'=>['required','string','max:32'],'platform'=>['required','in:Windows,macOS,Linux'],'architecture'=>['required','in:x64,ARM64'],'channel'=>['required','in:Stable,Beta,Nightly'],'notes'=>['nullable','string','max:5000'],'package'=>[($requireFile?'required':'nullable'),'file','max:1048576']];$rules['version'][]=Rule::unique('releases','version')->where(fn($q)=>$q->where('software_project_id',$r->integer('software_project_id'))->where('platform',$r->string('platform'))->where('architecture',$r->string('architecture')))->ignore($release?->id);return $r->validate($rules);}
}
