@extends('admin.layout',['heading'=>'Marketplace Security Review'])
@section('content')
<div class="admin-page-head"><div><p class="admin-kicker">{{ strtoupper($submission->item->project->name) }} · {{ strtoupper($submission->item->item_type) }}</p><h2>{{ $submission->item->name }} · v{{ $submission->release?->version }}</h2><p class="muted">Submitted by {{ $submission->submitter->name }} · {{ optional($submission->submitted_at)->format('d M Y H:i') }}</p></div><div class="review-header-badges"><span class="status-pill status-{{ strtolower($submission->status) }}">{{ str_replace('_',' ',$submission->status) }}</span><span class="risk-pill risk-{{ strtolower($submission->risk_level) }}">{{ $submission->risk_level }} · {{ $submission->risk_score }}/100</span></div></div>
<div class="review-detail-grid"><section class="review-detail-panel"><div class="panel-heading"><h3>Package & publisher</h3><span>{{ $submission->item->vendor ?: 'Community publisher' }}</span></div><dl class="review-dl"><dt>Stable ID</dt><dd>{{ $submission->item->item_id }}</dd><dt>Package</dt><dd>{{ $submission->release?->file_name ?: 'Missing' }}</dd><dt>Size</dt><dd>{{ number_format(($submission->release?->file_size??0)/1048576,1) }} MB</dd><dt>SHA-256</dt><dd><code>{{ $submission->release?->sha256 }}</code></dd><dt>Compatibility</dt><dd>{{ $submission->release?->platform }} · {{ $submission->release?->architecture }} · {{ $submission->release?->channel }}</dd><dt>App range</dt><dd>{{ $submission->release?->minimum_app_version ?: 'Any' }} → {{ $submission->release?->maximum_app_version ?: 'Any' }}</dd></dl></section>
<section class="review-detail-panel"><div class="panel-heading"><h3>Declared permissions</h3><span>Developer declaration</span></div>@forelse($submission->item->permissions??[] as $permission)<div class="permission-row"><span>{{ $permission }}</span><small>{{ str_contains(strtolower($permission),'network')?'External network access':(str_contains(strtolower($permission),'write')?'Writes project/files':'Declared capability') }}</small></div>@empty<p class="muted">No elevated permissions declared.</p>@endforelse</section></div>
<section class="review-detail-panel"><div class="panel-heading"><h3>Automated risk assessment</h3><span>{{ $submission->risk_summary }}</span></div><div class="risk-grid">@foreach($submission->risks as $risk)<div class="risk-check"><div><strong>{{ ucwords(str_replace('_',' ',$risk->category)) }}</strong><small>{{ $risk->summary }}</small></div><span class="risk-pill risk-{{ strtolower($risk->status) }}">{{ $risk->status }} · {{ $risk->score }}</span></div>@endforeach</div><form class="risk-edit" method="POST" action="{{ route('admin.marketplace.review.risk',$submission) }}">@csrf @method('PATCH')<select name="category" required>@foreach(['package_integrity','permissions','package_type','archive_scan','publisher','dependencies','content'] as $v)<option>{{ $v }}</option>@endforeach</select><select name="status"><option>PASS</option><option>REVIEW</option><option>FAIL</option></select><input type="number" name="score" min="0" max="100" value="0"><select name="risk_level"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select><input name="notes" placeholder="Admin security note"><button class="admin-button">Update risk</button></form></section>
<section class="review-detail-panel"><div class="panel-heading"><h3>Developer submission message</h3></div><p class="review-message-text">{{ $submission->developer_message ?: 'No message provided.' }}</p></section>
@if(in_array($submission->status,['SUBMITTED','UNDER_REVIEW']))<section class="decision-panel"><div><span class="admin-kicker">FINAL MODERATION DECISION</span><h3>Do not publish until you are satisfied with the package.</h3><p>Approval publishes this release to the public marketplace. Requesting changes keeps it private and sends feedback to the developer.</p></div>@if($submission->status==='SUBMITTED')<form method="POST" action="{{ route('admin.marketplace.review.start',$submission) }}">@csrf<button class="admin-button primary">Start review</button></form>@endif<form class="decision-form" method="POST" action="{{ route('admin.marketplace.review.decide',$submission) }}" onsubmit="const b=this.querySelector('button[type=submit]'); if(b){b.disabled=true; b.textContent='Recording decision…';}">@csrf<select name="decision" required><option value="" selected disabled>Select a moderation decision…</option><option value="needs_changes">Request changes</option><option value="reject">Reject</option><option value="approve">Approve & publish</option></select><textarea name="reason" required rows="4" placeholder="Explain the decision. This is shown to the developer."></textarea><button type="submit" class="admin-button primary">Record decision</button></form></section>@endif
@if($submission->status==='PUBLISHED')<section class="decision-panel"><div><h3>This release is public.</h3><p>It is currently available to compatible Lumina/DBNavigator clients.</p></div><form method="POST" action="{{ route('admin.marketplace.review.unpublish',$submission) }}" onsubmit="return confirm('Unpublish this release? It will no longer be publicly available to Lumina/DBNavigator clients.');">@csrf<button type="submit" class="admin-button danger">Unpublish release</button></form></section>@endif
<section class="review-detail-panel"><div class="panel-heading"><h3>Audit trail</h3></div><div class="timeline">@foreach($submission->logs->sortBy('created_at') as $log)<div><span>{{ $log->created_at->format('d M Y H:i') }}</span><strong>{{ ucwords(str_replace('_',' ',$log->action)) }}</strong><small>{{ $log->actor?->name ?: 'System' }}</small><p>{{ $log->comment }}</p></div>@endforeach</div></section>
@endsection
